
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

/************************************************
UNIDADE DE PROCESSAMENTO NEURAL FEITA POR MAIKE DE OLIVEIRA NASCIMENTO MONITOR DA DISCIPLINA DE SISTEMAS DIGITAIS

MODULO CRIADO PARA UTILIZAÇAO NA SEGUNDA UNIDADE DA DISCIPLINA COMO FORMA DE DAR CONTINUIDADE AO PROBLEMA 1 DO SEMESTRE DE 2026.1

*************************************************/

module problema1_sd(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// SMA //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED (High Active) //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY (Active Low) //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 (Low Active) //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// RS232 //////////
	input 		          		UART_CTS,
	output		          		UART_RTS,
	input 		          		UART_RXD,
	output		          		UART_TXD,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// I2C for EEPROM (I2C ADDRESS W/R = 0xA0/0xA1) //////////
	output		          		EEP_I2C_SCLK,
	inout 		          		EEP_I2C_SDAT,

	//////////// Ethernet //////////
	output		          		ENET_GTX_CLK,
	input 		          		ENET_INT_N,
	input 		          		ENET_LINK100,
	output		          		ENET_MDC,
	inout 		          		ENET_MDIO,
	output		          		ENET_RST_N,
	input 		          		ENET_RX_CLK,
	input 		          		ENET_RX_COL,
	input 		          		ENET_RX_CRS,
	input 		     [3:0]		ENET_RX_DATA,
	input 		          		ENET_RX_DV,
	input 		          		ENET_RX_ER,
	input 		          		ENET_TX_CLK,
	output		     [3:0]		ENET_TX_DATA,
	output		          		ENET_TX_EN,
	output		          		ENET_TX_ER,

	//////////// TV Decoder (I2C ADDRESS W/R = 0x40/0x41) //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// IR Receiver //////////
	input 		          		IRDA_RXD,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SSRAM //////////
	output		          		SSRAM_ADSC_N,
	output		          		SSRAM_ADSP_N,
	output		          		SSRAM_ADV_N,
	output		     [3:0]		SSRAM_BE,
	output		          		SSRAM_CLK,
	output		          		SSRAM_GW_N,
	output		          		SSRAM_OE_N,
	output		          		SSRAM_WE_N,
	output		          		SSRAM0_CE_N,
	output		          		SSRAM1_CE_N,

	//////////// Flash //////////
	output		          		FL_CE_N,
	output		          		FL_OE_N,
	output		          		FL_RESET_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N,

	//////////// Data and Address bus shared by Flash & SSRAM //////////
	output		    [26:1]		FS_ADDR,
	inout 		    [31:0]		FS_DQ,

	//////////// G-Sensor //////////
	input 		          		G_SENSOR_INT1,
	output		          		G_SENSOR_SCLK,
	inout 		          		G_SENSOR_SDAT,

	//////////// Fan Control //////////
	inout 		          		FAN_CTRL
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN

// =======================================================
//  Controladores de Latência das Memórias (4 Ciclos)
// =======================================================
wire req_pixel, req_win, req_bias, req_beta;

reg [3:0] delay_pixel;
reg [3:0] delay_win;
reg [3:0] delay_bias;
reg [3:0] delay_beta;

always @(posedge CLOCK_50) begin
    // Se a FSM está pedindo pixel, empurra '1'. Se não, zera tudo.
    if (req_pixel) delay_pixel <= {delay_pixel[2:0], 1'b1};
    else delay_pixel <= 4'd0;

    if (req_win) delay_win <= {delay_win[2:0], 1'b1};
    else delay_win <= 4'd0;

    if (req_bias) delay_bias <= {delay_bias[2:0], 1'b1};
    else delay_bias <= 4'd0;
          
    if (req_beta) delay_beta <= {delay_beta[2:0], 1'b1};
    else delay_beta <= 4'd0;
end

// O dado está disponível exatamente no 4º ciclo (quando o bit 3 vira 1)
wire is_avaliable_pixel = delay_pixel[3];
wire is_avaliable_win   = delay_win[3];
wire is_avaliable_bias  = delay_bias[3];
wire is_avaliable_beta  = delay_beta[3];

// =======================================================
//  DECLARAÇÃO DE TODOS OS FIOS DE INTERCONEXÃO
// =======================================================
// Fios de Endereço
wire [16:0] addr_win;
wire [10:0] addr_beta;
wire [9:0]  addr_pixel;
wire [6:0]  addr_bias;

// Fios de Dados e Habilitação
wire signed [15:0] data_from_bias;
wire signed [15:0] data_from_win;
wire signed [15:0] data_from_beta;
wire [7:0] data_from_pixeis;

//Fio para o digito vencedor em binario
wire [3:0] winner;

//Fios de habilitaçao e sinalizaçao do encerramento da FMS
wire enable;
wire done_unit;

// =======================================================
//  INSTANCIAÇÃO DAS MEMÓRIAS (BRAM / ROM)
// =======================================================
	//Memoria ram que armazena a matriz de valores de beta
    ram_beta (
        .address(addr_beta),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_beta)
    );
    
	 //Memoria ram que armazena a matriz de valores do bias
    ram_bias (
        .address(addr_bias),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_bias)
    );
    
	 
	 //memoria ram que armazena a matriz de valores de pesos
    ram_win(
        .address(addr_win),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_win)
    );
    
	 //memoria ram que armazena a imagem a ser computada pela rede neural
    ram_img (
        .address(addr_pixel),
        .clock(CLOCK_50),
        .data(8'd0), 
        .wren(1'b0),
        .q(data_from_pixeis)
    );
    
	 
	 //criaçao do sinal de enable e instanciamento do led como output da maquina de estados
	 assign enable = SW[0] & !done_unit;
	 assign LEDR[0] = done_unit;
	 
	 /*******************************************************************
	 Instanciamento da unidade neural responsavel por realizar todos os calculos necessarios
	 para a inferencia de qual numero esta contido na imagem	 
	 *******************************************************************/
	 neural_unit(
		.addr_mem_bias(addr_bias),
		.addr_mem_pixel(addr_pixel),
		.addr_mem_win(addr_win),
		.addr_mem_beta(addr_beta),
		.req_bias(req_bias),
		.req_win(req_win),
		.req_beta(req_beta),
		.req_pixel(req_pixel),
		.is_available_bias(is_avaliable_bias),
		.is_available_beta(is_avaliable_beta),
		.is_available_win(is_avaliable_win),
		.is_available_pixel(is_avaliable_pixel),
		.data_in_bias(data_from_bias),
		.data_in_beta(data_from_beta),
		.data_in_win(data_from_win),
		.data_in_pixel(data_from_pixeis),
		.clk(CLOCK_50),
		.enable(enable),
		.rst(SW[1]),
		.output_digit(winner),
		.done(done_unit)
	);
	
	//modulo para exibçao no display de 7 segmentos do valor que foi inferido pela rede neural
    display_resultado visor_ia (
        .resultado_bin(winner), 
        .hex_out(HEX0)                   
    );

endmodule
