
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module problema1_sd(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// SMA //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED (High Active) //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY (Active Low) //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 (Low Active) //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// RS232 //////////
	input 		          		UART_CTS,
	output		          		UART_RTS,
	input 		          		UART_RXD,
	output		          		UART_TXD,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// I2C for EEPROM (I2C ADDRESS W/R = 0xA0/0xA1) //////////
	output		          		EEP_I2C_SCLK,
	inout 		          		EEP_I2C_SDAT,

	//////////// Ethernet //////////
	output		          		ENET_GTX_CLK,
	input 		          		ENET_INT_N,
	input 		          		ENET_LINK100,
	output		          		ENET_MDC,
	inout 		          		ENET_MDIO,
	output		          		ENET_RST_N,
	input 		          		ENET_RX_CLK,
	input 		          		ENET_RX_COL,
	input 		          		ENET_RX_CRS,
	input 		     [3:0]		ENET_RX_DATA,
	input 		          		ENET_RX_DV,
	input 		          		ENET_RX_ER,
	input 		          		ENET_TX_CLK,
	output		     [3:0]		ENET_TX_DATA,
	output		          		ENET_TX_EN,
	output		          		ENET_TX_ER,

	//////////// TV Decoder (I2C ADDRESS W/R = 0x40/0x41) //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// IR Receiver //////////
	input 		          		IRDA_RXD,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SSRAM //////////
	output		          		SSRAM_ADSC_N,
	output		          		SSRAM_ADSP_N,
	output		          		SSRAM_ADV_N,
	output		     [3:0]		SSRAM_BE,
	output		          		SSRAM_CLK,
	output		          		SSRAM_GW_N,
	output		          		SSRAM_OE_N,
	output		          		SSRAM_WE_N,
	output		          		SSRAM0_CE_N,
	output		          		SSRAM1_CE_N,

	//////////// Flash //////////
	output		          		FL_CE_N,
	output		          		FL_OE_N,
	output		          		FL_RESET_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N,

	//////////// Data and Address bus shared by Flash & SSRAM //////////
	output		    [26:1]		FS_ADDR,
	inout 		    [31:0]		FS_DQ,

	//////////// G-Sensor //////////
	input 		          		G_SENSOR_INT1,
	output		          		G_SENSOR_SCLK,
	inout 		          		G_SENSOR_SDAT,

	//////////// Fan Control //////////
	inout 		          		FAN_CTRL
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



	//////////// FAN Control //////////
assign FAN_CTRL = 1'bz; // turn on FAN

// =======================================================
//  Controladores de Latência das Memórias (4 Ciclos)
// =======================================================
wire req_pixel, req_win, req_bias, req_beta;

reg [3:0] delay_pixel;
reg [3:0] delay_win;
reg [3:0] delay_bias;
reg [3:0] delay_beta;

always @(posedge CLOCK_50) begin
    // Se a FSM está pedindo pixel, empurra '1'. Se não, zera tudo.
    if (req_pixel) delay_pixel <= {delay_pixel[2:0], 1'b1};
    else delay_pixel <= 4'd0;

    if (req_win) delay_win <= {delay_win[2:0], 1'b1};
    else delay_win <= 4'd0;

    if (req_bias) delay_bias <= {delay_bias[2:0], 1'b1};
    else delay_bias <= 4'd0;
          
    if (req_beta) delay_beta <= {delay_beta[2:0], 1'b1};
    else delay_beta <= 4'd0;
end

// O dado está disponível exatamente no 4º ciclo (quando o bit 3 vira 1)
wire is_avaliable_pixel = delay_pixel[3];
wire is_avaliable_win   = delay_win[3];
wire is_avaliable_bias  = delay_bias[3];
wire is_avaliable_beta  = delay_beta[3];

// =======================================================
//  DECLARAÇÃO DE TODOS OS FIOS DE INTERCONEXÃO
// =======================================================
// Fios de Endereço
wire [16:0] addr_win;
wire [10:0] addr_beta;
wire [9:0]  addr_pixel;
wire [6:0]  addr_bias;
wire [6:0]  addr_w;
wire [6:0]  addr_rd_reg;
wire [3:0]  addr_reg;
wire [3:0]  addr_to_rd_points;

// Fios de Dados e Habilitação
wire w_en;
wire w_en2;
wire signed [15:0] data_to_raw;
wire signed [15:0] data_to_raw_sd;
wire signed [15:0] data_from_bias;
wire signed [15:0] data_from_win;
wire signed [15:0] data_from_beta;
wire signed [15:0] data_from_register;
wire signed [15:0] points_readed;
wire [7:0] data_from_pixeis;

// Fios do Argmax
wire [3:0] digito_vencedor;
wire argmax_terminou;

// =======================================================
//  INSTANCIAÇÃO DAS MEMÓRIAS (BRAM / ROM)
// =======================================================
    ram_beta (
        .address(addr_beta),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_beta)
    );
    
    ram_bias (
        .address(addr_bias),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_bias)
    );
    
    ram_win(
        .address(addr_win),
        .clock(CLOCK_50),
        .wren(1'b0),
        .q(data_from_win)
    );
    
    ram_img (
        .address(addr_pixel),
        .clock(CLOCK_50),
        .data(8'd0), 
        .wren(1'b0),
        .q(data_from_pixeis)
    );
    
	 
	 wire enable;
	 
	 wire done_unit;
	 
	 assign enable = SW[0] & !done_unit;
	 assign LEDR[0] = done_unit;
	 
	 neural_unit(
		.addr_mem_bias(addr_bias),
		.addr_mem_pixel(addr_pixel),
		.addr_mem_win(addr_win),
		.addr_mem_beta(addr_beta),
		.req_bias(req_bias),
		.req_win(req_win),
		.req_beta(req_beta),
		.req_pixel(req_pixel),
		.is_available_bias(is_avaliable_bias),
		.is_available_beta(is_avaliable_beta),
		.is_available_win(is_avaliable_win),
		.is_available_pixel(is_avaliable_pixel),
		.data_in_bias(data_from_bias),
		.data_in_beta(data_from_beta),
		.data_in_win(data_from_win),
		.data_in_pixel(data_from_pixeis),
		.clk(CLOCK_50),
		.enable(enable),
		.rst(SW[1]),
		.output_digit(winner),
		.done(done_unit)
	);
	wire [3:0] winner;
	/* wire enable_fr_layer, enable_sd_layer;
	 wire fr_iteration_done, sd_iteration_done;
	 wire [4:0] iteration_counter;
	 wire sd_iteration_counter;
	 wire acabou;
	 
	 assign acabou = (addr_w == 7'd127) ? 1'b1: 1'b0;
	 
	 wire acabou2;
	 assign acabou2 = (addr_reg == 4'd9) ? 1'b1:1'b0;
	 
	 wire enable_agg;
	 
	 assign LEDR[0] = fr_iteration_done;
	 assign LEDR[2] = sd_iteration_done;
	 
	 assign LEDR[1] = enable_fr_layer;
	 assign LEDR[3] = enable_sd_layer;
	 
// =======================================================
//  INSTANCIAÇÃO DAS CAMADAS NEURAIS
// =======================================================    
    first_layer modulo_teste(
        .done(fr_iteration_done),
        .iteration_counter(iteration_counter),
        .enable(SW[7]),
        .addr_pixel(addr_pixel),
        .addr_win(addr_win),
        .addr_bias(addr_bias),
        .clk(CLOCK_50),
        .rst(SW[8]),
        .addr_to_raw_in_register(addr_w),
        .data_to_raw_in_register(data_to_raw),
        .enable_register_write(w_en),
        
        .req_pixel(req_pixel),
        .req_win(req_win),
        .req_bias(req_bias),
        .is_avaliable_pixel(is_avaliable_pixel),
        .is_avaliable_win(is_avaliable_win),
        .is_avaliable_bias(is_avaliable_bias),
        
        .data_in_win(data_from_win),
        .data_in_bias(data_from_bias),
        .data_in_pixel(data_from_pixeis)
    );

    reg_bank128 reg_first_layer(
        .addr_r(addr_rd_reg),
        .addr_w(addr_w),
        .data_in(data_to_raw),
        .data_out(data_from_register),
        .wr_en(w_en),
        .clk(CLOCK_50)
    );
	 

    second_layer sd_layer(
        .addr_beta(addr_beta),
        .addr_register(addr_rd_reg),
        .data_in_beta(data_from_beta),
        .data_in_register(data_from_register),
        .addr_register_raw(addr_reg),
        .data_register_raw(data_to_raw_sd),
        .enable_register_write(w_en2),
        .done(sd_iteration_done),
        .iteration_counter(sd_iteration_counter), // <-- Verifique o tamanho disto na sua second_layer!
        .clk(CLOCK_50),
        .enable(SW[7]),
        .rst(SW[8]),                 // <-- CORRIGIDO AQUI!
        .req_beta(req_beta),
        .is_avaliable_beta(is_avaliable_beta),
    );

    reg_bank10 reg_second_layer(
        .addr_r(SW[3:0]),
        .addr_w(addr_reg),
        .data_in(data_to_raw_sd),
        .data_out(points_readed),
        .wr_en(w_en2),
        .clk(CLOCK_50)
    );

	 
	 wire signed [15:0] data_to_display;
// =======================================================
//  PERIFÉRICOS DE DEBUG (Display)
// =======================================================
    conversor_q4_12_display debug_display (
        .q4_12_in(points_readed), 
        .HEX5(HEX5),
        .HEX4(HEX4),
        .HEX3(HEX3),
        .HEX2(HEX2),
        .HEX1(HEX1),
        .HEX0(HEX0)
    );*/

	 
    /*argmax_iterativo juiz_final (
        .clk(CLOCK_50),
        .rst(SW[8]), 
        .enable(SW[7]), 
        .addr_r(addr_to_rd_points), 
        .data_in(points_readed),
        .predicted_digit(digito_vencedor), 
        .done(arg_done)
    );
	 
	 reg [3:0] winner;
	 wire arg_done; */

    display_resultado visor_ia (
        .resultado_bin(winner), 
        .hex_out(HEX0)                   
    );

endmodule
